discourse_mini_mod:
  mini_mod_enabled:
    default: false
    client: true
  mini_mod_manage_all_categories:
    default: false
    client: true
  mini_mod_manage_tags:
    default: false
    client: true
  mini_mod_can_post_in_closed_topics:
    default: false
    client: false
  mini_mod_can_reopen_topics:
    default: false
    client: false
  mini_mod_tl4_can_post_in_closed_topics:
    default: false
    client: false
